name: Flight Monitor

on:
 workflow_dispatch:
 schedule:
 - cron: '0 7 * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install
   
      - name: Run bot
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python flight_tracker.py

      - name: Commit prices.csv
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add prices.csv
          git commit -m "Update prices history" || echo "No changes"

      - name: Push changes
        run: git push
